export const datagjobs=[
    {
        job_title:"IOCL 2023 Recruitment For Junior Engineering Assistant ",
        job_description:"this job is for supports engineers in tasks like maintenance, troubleshooting, and system operation, ensuring smooth operations and assisting with various engineering activities.",
        job_min_salary:"25000",
        job_max_salary:"56000",
        job_city:"West Bengal, and Gujarat, India",
        job_publisher:"IndianOil",
        job_employment_type:"Junior Engineering Assistant",
        job_apply_link:"https://ioclapply.com/",
        job_id:1,
        "job_cat": "govt",
    },
    {
        job_title:"Apply Online for 441 Trade Apprentice & Technician Apprentice Posts",
        job_description:"Indian Oil Corporation Limited (IOCL), Eastern Region has declared the notification for the recruitment of Technician & Trade Apprentice vacancies. Qualification required is Matric with ITI (Relevant Engg Disciplines), Graduation, Diploma in Relevant Engg Disciplines. The minimum age limit will be 18 years and maximum will be 24 yea ",
        job_min_salary:"25,000",
        job_max_salary:"65,000",
        job_city:"Kolkata, West Bengal",
        job_publisher:"Indian Oil Corporation Limited",
        job_employment_type:"Trade Apprentice & Technician Apprentice",
        job_apply_link:"https://www.iocrefrecruit.in/iocrefrecruit/main_special_oct21.aspx",
        job_id:2,
        "job_cat": "govt",
    },
    {
        job_title:"IOCL Recruitment 2023: Government Job Vacancy",
        job_description:"Indian Oil Corporation Limited (IOCL) has released the notification for IOCL Recruitment 2023 on its official website at www.rojgarhunt.com. Through this recruitment drive a total of 1490 vacancies are to be filled for Technician, Trade Apprentices, and Accounts Executive/ Graduate Apprentice (Technical and Non-Technical) Posts at different locations in the States/UT of Tamilnadu & Puducherry, Karnataka, Kerala, Andhra Pradesh & Telangana. The IOCL Recruitment online application process has started The direct link to apply has been provided along with the requirements of the application form & steps to complete the form. ",
        job_min_salary:" 40,400",
        job_max_salary:" 82,560",
        job_city:"Kolkata, West Bengal",
        job_publisher:"Indian Oil Corporation Limited",
        job_employment_type:"Junior Assistant / Assistant / Engineer / Junior Engineer / Data Entry Operator / Computer Operator /",
        job_id:3,
        "job_cat": "govt",
        job_apply_link:"https://rojgarhire.com/job/iocl-recruitment-2023-72/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    },
    {
        job_title:"Financial Accountant",
        job_description:"I PERFORM THE WORK ON DAILY BASIS,I DO THE WORK WITH PROPER MANNER AND DIGNITY,I MAINTAIN TO COMLETE MY DUTIES WITH PROPER TIME,I COMPLETE ALL THE WORK WITH BEST TIME MANAGEMENT MANNER,BESIDES I CAN NOT QUIT THIS JOB.",
        job_min_salary:"44,000",
        job_max_salary:"82,000",
        job_city:"Howrah, West Bengal",
        job_publisher:"Indian Oil Corporation Limited",
        job_employment_type:"Financial Accountant",
        job_id:4,
        "job_cat": "govt",
        job_apply_link:"https://www.simplyhired.co.in/job/3gbRudn-a65wCkwvwYBhjdMTjWiGX9TDdtgKWORvRkq44ULqn2q6Qw?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    },
    {
        job_title:"Coal India Executive Recruitment 2023 ",
        job_description:"Coal India Executive Recruitment 2023, Coal india executive recruitment 2023 hindi apply online, coal india limited recruitment 2023, ",
        job_min_salary:"35,400",
        job_max_salary:"65,500",
        job_city:"Kolkata, West Bengal",
        job_publisher:"Coal India Limited",
        job_employment_type:"Coal India Executive",
        job_id:5,
        "job_cat": "govt",
        job_apply_link:"https://getgovt.com/coal-india-executive-recruitment-registration-apply/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    },
    {
        job_title:"Coal India Recruitment 2023 Apply Online For 560 Posts",
        job_description:"Coal India Recruitment 2023: Coal India Limited (CIL) has released the official Coal India Recruitment 2023 Notification PDF for 560 vacancies for the post of Management Trainee",
        job_min_salary:"32,000",
        job_max_salary:"55,000",
        job_city:"Kolkata, West Bengal",
        job_publisher:"Coal India Limited (CIL)",
        job_employment_type:"Management Trainee (MT)",
        job_id:6,
        "job_cat": "govt",
        job_apply_link:"https://govjobyojana.com/coal-india-recruitment/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    },
    {
        job_title:"Gujarat metro",
        job_description:"Want to do work in the Gujarat Metro Rail Limited Railway department then, now you have a great chance to start doing a career in Indian railway department with the Posts of Chief General Manager/ General Manager , Addl. General Manager/Joint General Manager , Sr. Deputy General Manager/Deputy General Manager , Sr. Deputy General Manager/Deputy General Manager , Manager/Asst. Manager , General Manager, Manager/Asst.Manager, Engineer – Sr. Grade, Asst. Manager (HR), various posts and get selected on the basis of the Personal Interview & Document verification.",
        job_min_salary:"40,000",
        job_max_salary:"67,000",
        job_city:"Gujarat",
        job_publisher:"Indian Railway",
        job_employment_type:"General Manager, Asst Manager & Other",
        job_id:7,
        "job_cat": "govt",
        job_apply_link:"https://indianrailwayrecruitment.in/jobs-in-gujarat-metro-rail-out-gmrc-10th-pass-b-e-b-tech-82-vacancy-get-salary-upto-280000/",
    },
    {
        job_title:"Central railway",
        job_description:"Want to do work in the RRC CR Railway department then, now you have a great chance to start doing a career in Indian railway department with the Posts of Level 1 & 2 of Pay Matrix 7th CPC against scouts and guides Quota and get selected on the basis of the written exam and Marks on Certificates . As RRC Central Railway department invites ONLINE applications from the following for filling up Two (02) posts in level 2 and Ten (10) posts (i.e. 02 posts each for Mumbai, Bhusawal, Nagpur, Pune and Solapur Division) in level 1 against Scouts and Guides Quota for the year 2023-24 over Central Railway. ",
        job_min_salary:"50,000",
        job_max_salary:"1,00,500",
        job_city:"Mumbai, Bhusawal, Nagpur, Pune and Solapur ",
        job_publisher:"Indian Railway",
        job_employment_type:"Level 1 & 2",
        job_id:8,
        "job_cat": "govt",
        job_apply_link:"https://indianrailwayrecruitment.in/central-railway-scouts-and-guides-recruitment-2023/",
    },
    {
        job_title:"BMRCL",
        job_description:"Want to work in the Railway department then, now you have a great chance to start a career in the Indian railway department with the Post of Station Controller / Train Operator , Section Engineer , Maintainer, Deputy Chief Engineer , Executive Engineer , Assistant Executive Engineer , Assistant Engineer and various Jobs, and get selected on the basis of Written Exam and Interview.",
        job_min_salary:"10,000",
        job_max_salary:"15,000",
        job_city:"Bangalore ",
        job_publisher:"Indian Railway",
        job_employment_type:"Various",
        job_id:9,
        "job_cat": "govt",
        job_apply_link:"https://indianrailwayrecruitment.in/bmrcl-recruitment-bmrc-co/",
    },
    {
        job_title:"BHEL Recruitment 2023 for Project Engineers & Project Supervisors ",
        job_description:"BHEL Recruitment 2023: Bharat Heavy Electricals Limited has announced notification for the post of Project Engineer/Project Supervisor for a fixed period of two yea Candidates with B.E/B.Tech/Diploma are eligible for this post. There are 11 vacancies for this job. Interested and eligible candidates can apply online. The detailed eligibility and selection process are explained below.",
        job_min_salary:" 46,130",
        job_max_salary:" 82,620",
        job_city:"Visakhapatnam",
        job_publisher:"BHEL",
        job_employment_type:"Project Engineers & Project Supervisors",
        job_id:10,
        "job_cat": "govt",
        job_apply_link:"https://www.freshersvoice.com/bhel-recruitment/",
    },
    {
        job_title:"BHEL Recruitment 2023 – Apply Online for 10 Project Supervisor Posts",
        job_description:"HEL Recruitment 2023: Apply for 10 Project Supervisor vacancies. Bharat Heavy Electricals Limited invited applications from eligible and interested candidates to fill up Project Supervisor Posts through BHEL official notification April 2023. Job seekers who are looking for a career in Bengaluru – Karnataka Government can make use of this opportunity. Interested candidates can Apply Online & Offline.",
        job_min_salary:" 43,550",
        job_max_salary:" 62,620",
        job_city:"Bengaluru – Karnataka",
        job_publisher:"BHEL",
        job_employment_type:"Project Supervisor",
        job_id:11,
        "job_cat": "govt",
        job_apply_link:"https://www.karnatakacareein/bhel-recruitment-2023-apply-online-for-10-project-supervisor/",
    },
    {
        job_title:"BHEL Recruitment - Engineer/Executive Trainee Vacancies",
        job_description:"BHEL Recruitment 2022: Apply for 150 Engineer/Executive Trainee vacancies. Bharat Heavy Electricals Limited invited applications from eligible and interested candidates to fill up Engineer/Executive Trainee Posts through BHEL official notification September 2022. Job seekers who are looking for a career in All India Government can make use of this opportunity. ",
        job_min_salary:" 50,000",
        job_max_salary:" 180,000",
        job_city:" All India",
        job_publisher:"BHEL",
        job_employment_type:"Engineer/Executive Trainee",
        job_id:12,
        "job_cat": "govt",
        job_apply_link:"https://www.karnatakacareein/bhel-recruitment-2022-apply-online-for-150-engineer-executive-trainee/",
    },
    {
        job_title:"BHEL Recruitment - Apprentice Vacancies",
        job_description:"BHEL Recruitment 2022: Apply for 575 Apprentice vacancies. Bharat Heavy Electricals Limited invited applications from eligible and interested candidates to fill up Apprentice Posts through BHEL official notification August 2022. Job seekers who are looking for a career in Tiruchirappalli – Tamil Nadu Government can make use of this opportunity.",
        job_min_salary:" 7,700",
        job_max_salary:" 9,000",
        job_city:"Tiruchirappalli – Tamil Nadu",
        job_publisher:"BHEL",
        job_employment_type:"Apprentice",
        job_id:13,
        "job_cat": "govt",
        job_apply_link:"https://www.karnatakacareein/bhel-recruitment-2022-apply-online-for-575-apprentice/",
    },
    {
        job_title:"BHEL Recruitment - Part-Time Medical Consultants Vacancies",
        job_description:"BHEL Recruitment 2022: Apply for 01 Part-Time Medical Consultants vacancy. Bharat Heavy Electricals Limited invited applications from eligible and interested candidates to fill up Part-Time Medical Consultants Posts through BHEL official notification December 2022. Job seekers who are looking for a career in Bangalore – Karnataka Government can make use of this opportunity. ",
        job_min_salary:"44,000",
        job_max_salary:"64,000",
        job_city:" Bangalore – Karnataka",
        job_publisher:"BHEL",
        job_employment_type:" Part-Time Medical Consultants",
        job_id:14,
        "job_cat": "govt",
        job_apply_link:"https://www.karnatakacareein/bhel-recruitment-2023-apply-for-01-part-time-medical-consultants/",
    },
    {
        job_title:"Junior Research Fellow",
        job_description:"IIIT Sri City Recruitment 2023 invites applications for the 01 Junior Research Fellow position. To be eligible to apply for these posts, candidates must have completed their Graduation and Post Graduation. Interested and eligible candidates must submit their applications on or before 26/10/2023.",
        job_min_salary:" 31,000",
        job_max_salary:" 42,000",
        job_city:"Chittoor",
        job_publisher:"Indian Institute of Information Technology Sri City",
        job_employment_type:"Contract Basis",
        job_id:15,
        "job_cat": "govt",
        job_apply_link:"https://www.employeeadda.com/job/iiit-sri-city-jobs-2023-apply-online-for-01-junior-research-fellow-post/50537/",
    },
    {
        job_title:"NTPC Jobs 2023 ",
        job_description:"NTPC Recruitment 2023 invites applications for the 495 Graduate Engineers positions. To be eligible to apply for these posts, candidates must have completed their Graduation. Interested and eligible candidates must submit their applications on or before 20/10/2023.",
        job_min_salary:" 40,000",
        job_max_salary:" 1,40,000",
        job_city:"	All over India",
        job_publisher:"NTPC",
        job_employment_type:"Graduate Engineers",
        job_id:16,
        "job_cat": "govt",
        job_apply_link:"https://www.employeeadda.com/job/ntpc-jobs-2023-apply-online-for-495-graduate-engineers-posts/50511/",
    },
    ]
